@extends('backend.content')

@section('content')

	<h4>Digital Millennium Copyright Act</h4>
	<hr>

	<p>

	Watch Free Movies respects copyright law and expects its users to do the same. In accordance with the Digital Millennium Copyright Act (“DMCA”), the text of which may be found on the U.S. Copyright Office web site at http://www.copyright.gov/legislation/dmca.pdf , Watch Free Movies will respond expeditiously to notices of alleged copyright infringement that are reported to Watch Free Movies Designated Copyright Agent, identified in the sample Notice below. To file a copyright infringement notification with Watch Free Movies (“Notice”), you will need to send a written communication that includes substantially the following (please consult your legal counsel or see Section 512(c)(3) of the DMCA to confirm these requirements): · A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. · Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site. · Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material. Providing URLs in the body of an email is the best way to help us locate content quickly. · Information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted. · A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law. · A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. Deliver this Notice, with all items completed, to Watch Free Movies Contact us Tab and select DMCA in the drop down menu. Please note that under Section 512(f) of the DMCA, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability for damages. Please also note that the information provided in this legal Notice may be forwarded to the person who provided the allegedly infringing content. Watch Free Movies does not permit copyright infringing activities on its websites and will, if properly notified that files infringe a copyright, remove or disable access to such files. Watch Free Movies reserves the right to remove or disable access to files or links to allegedly infringing material without prior notice.

	</p>

@endsection